version: "3.7"

services:
  app:
    build:
      context: ../../
      dockerfile: .devcontainer/turing/Dockerfile
    command: sleep infinity
    user: vscode
    volumes:
      - /home/vscode/workspace/.venv
    ports:
      - "5400:5400"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

